VolunteerOrganizer/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace VolunteerOrganizer.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VolunteerOrganizer/Pages/EventEditor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolunteerOrganizer.Library;
using Microsoft.Data.SqlClient;
using System.Data;

namespace VolunteerOrganizer.Pages
{
    public class EventEditorModel : PageModel
    {
        public bool Editing { get; set; }
        public Event CurrentEvent { get; set; }
        public User LoggedInUser { get; set; }
        public List<Project> EventProjects { get; set; }
        // This list has the IndividualGUID and name of event's volunteers
        public List<(Guid, string, Guid)> EventVolunteers { get; set; }

        public EventEditorModel()
        {
            this.CurrentEvent = new Event();
            this.LoggedInUser = new User();
            this.Editing = false;
            this.EventProjects = new List<Project>();
            this.EventVolunteers = new List<(Guid, string, Guid)>();
        }

        public void OnGet(string eventId, string userId)
        {
            this.SetValues(eventId, userId);
        }

        public void OnPostEditEvent(string eventId, string userId)
        {
            this.SetValues(eventId, userId);

            this.Editing = true;
        }

        public void OnPostFinishEditing(string eventId, string userId)
        {
            this.SetValues(eventId, userId);

            string eventName = Request.Form["eventNameText"];
            string eventDescription = Request.Form["eventDescriptionText"];

            DateTime.TryParse(Request.Form["eventStartDate"].ToString(), out DateTime startDate);
            DateTime.TryParse(Request.Form["eventEndDate"].ToString(), out DateTime endDate);

            //DateTime startDate = DateTime.Parse((string)Request.Form["eventStartDate"]);
            //DateTime endDate = DateTime.Parse((string)Request.Form["eventEndDate"]);

            // Check to make sure that the given DateTimes are within SQL's acceptable ranges
            if (startDate < DateTime.Parse("01/01/1753") || startDate > DateTime.Parse("12/31/9999"))
            {
                startDate = DateTime.Parse("1/1/2000");
            }

            if (endDate < DateTime.Parse("01/01/1753") || endDate > DateTime.Parse("12/31/9999"))
            {
                endDate = DateTime.Parse("1/1/2000");
            }

            // Update the Event in the database
            SqlCommand eventUpdateCommand = new SqlCommand(
                "update Event " +
                "set EventName = @EventName, EventDescription = @EventDescription, StartDate = @StartDate, EndDate = @EndDate " +
                "where EventGUID = @EventGUID");
            eventUpdateCommand.Parameters.AddWithValue("@EventName", eventName);
            eventUpdateCommand.Parameters.AddWithValue("@EventDescription", eventDescription);
            eventUpdateCommand.Parameters.AddWithValue("@StartDate", startDate.ToString());
            eventUpdateCommand.Parameters.AddWithValue("@EndDate", endDate.ToString());
            eventUpdateCommand.Parameters.AddWithValue("@EventGUID", eventId);

            SQLWorker.ExecuteNonQuery(eventUpdateCommand);

            // Recreate the current event with the new data
            //this.CurrentEvent = new Event(eventName, eventDescription, startDate, endDate, Guid.Parse(eventId));

            this.Editing = false;
        }

        public void OnPostNewProject(string eventId, string userId)
        {
            this.SetValues(eventId, userId);

            Response.Redirect($"/ProjectEditor/{this.CurrentEvent.EventGUID}");
        }

        private void SetValues(string eventId, string userId)
        {
            // Assign the values provided to maintain data between posts
            this.CurrentEvent = new Event(Guid.Parse(eventId));
            this.LoggedInUser = new User(Guid.Parse(userId));

            // Query the database to get all of the projects associated with the current event
            SqlCommand projectQuery = new SqlCommand("select TaskGUID from Task where EventGUID = @EventGUID");
            projectQuery.Parameters.AddWithValue("@EventGUID", this.CurrentEvent.EventGUID);

            DataTable projectResults = SQLWorker.ExecuteQuery(projectQuery);

            // Assign the projects into the EventProjects
            for (int i = 0; i < projectResults.Rows.Count; i++)
            {
                this.EventProjects.Add(new Project((Guid)projectResults.Rows[i][0]));
            }

            // Query the database to get all of the individuals volunteering for the current event
            SqlCommand volunteerQuery = new SqlCommand(
                "select Individual.IndividualGUID, UserData.FirstName, UserData.LastName, UserData.UserGUID " +
                "from Individual " +
                "inner join UserData on Individual.UserGUID = UserData.UserGUID " +
                "where Individual.EventGUID = @EventGUID " +
                "and Individual.UserType = '02'");
            volunteerQuery.Parameters.AddWithValue("EventGUID", this.CurrentEvent.EventGUID);

            DataTable volunteerResults = SQLWorker.ExecuteQuery(volunteerQuery);

            for (int i = 0; i < volunteerResults.Rows.Count; i++)
            {
                Guid volunteerGUID = (Guid)volunteerResults.Rows[i][0];
                string volunteerName = $"{volunteerResults.Rows[i][1]} {volunteerResults.Rows[i][2]}";
                Guid userGuid = (Guid)volunteerResults.Rows[i][3];

                // If the volunteerGuid is a duplicate, don't insert it
                if (!this.EventVolunteers.Any(x => x.Item3 == userGuid))
                {
                    this.EventVolunteers.Add((volunteerGUID, volunteerName, userGuid));
                }
            }
        }
    }
}

VolunteerOrganizer/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolunteerOrganizer.Library;
using Microsoft.Data.SqlClient;
using System.Data;

namespace VolunteerOrganizer.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

VolunteerOrganizer/Pages/InstanceEditor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolunteerOrganizer.Library;
using Microsoft.Data.SqlClient;
using System.Data;

namespace VolunteerOrganizer.Pages
{
    public class InstanceEditorModel : PageModel
    {
        public bool ModifyingInstance { get; set; }
        public bool NewInstance { get; set; }
        public ProjectInstance WorkingInstance { get; set; }
        public Project WorkingProject { get; set; }

        public InstanceEditorModel()
        {
            this.ModifyingInstance = false;
            this.NewInstance = false;
            this.WorkingInstance = new ProjectInstance();
            this.WorkingProject = new Project();
        }

        public void OnGet(string projectId, string? instanceId)
        {
            this.SetValues(projectId, instanceId);
        }

        public void OnPostModifyInstance(string projectId, string? instanceId)
        {
            this.SetValues(projectId, instanceId);

            this.ModifyingInstance = true;
        }

        public void OnPostSaveInstance(string projectId, string? instanceId)
        {
            this.SetValues(projectId, instanceId);
        }

        private void SetValues(string projectId, string? instanceId)
        {
            this.WorkingProject = new Project(Guid.Parse(projectId));

            // If the instanceId is null, we are creating a new one
            if (instanceId == null)
            {
                this.ModifyingInstance = true;
                this.NewInstance = true;
            }
            else
            {
                this.WorkingInstance = new ProjectInstance(Guid.Parse(projectId));
                this.ModifyingInstance = false;
                this.NewInstance = false;
            }
        }
    }
}

VolunteerOrganizer/Pages/LogInPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolunteerOrganizer.Library;
using Microsoft.Data.SqlClient;
using System.Data;

namespace VolunteerOrganizer.Pages
{
    public class LogInPageModel : PageModel
    {
        public bool LogInError { get; set; }

        public void OnGet()
        {
            this.LogInError = false;
        }

        public void OnPost()
        {
            string userEmail = Request.Form["userEmailText"];
            string unhashedPassword = Request.Form["userPasswordText"];

            // Hash the given password from the request
            string userPassword = HashManager.HashString(unhashedPassword);

            SqlCommand command = new SqlCommand("select UserGuid from UserData where UserEmail = @UserEmail and UserPassword = @UserPassword");
            command.Parameters.AddWithValue("@UserEmail", userEmail);
            command.Parameters.AddWithValue("@UserPassword", userPassword);

            DataTable queryResult = SQLWorker.ExecuteQuery(command);

            // If there is exactly one result, that means that the user input correct data, and we can go to the landing page
            if (queryResult.Rows.Count == 1)
            {
                Response.Redirect("/LoggedInPage/" + queryResult.Rows[0][0].ToString());
            }
            else
            {
                this.LogInError = true;
            }
        }
    }
}

VolunteerOrganizer/Pages/ProjectEditor.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VolunteerOrganizer.Library;
using Microsoft.Data.SqlClient;
using System.Data;

namespace VolunteerOrganizer.Pages
{
    public class ProjectEditorModel : PageModel
    {
        public bool ModifyingProject { get; set; }
        public bool NewProject { get; set; }
        public bool AddingInstance { get; set; }
        public Project EditingProject { get; set; }
        public Event AssociatedEvent { get; set; }

        public ProjectEditorModel()
        {
            this.ModifyingProject = false;
            this.NewProject = false;
            this.AddingInstance = false;
            this.EditingProject = new Project();
            this.AssociatedEvent = new Event();
        }

        public void OnGet(string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);
        }

        public void OnPostEditProject(string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);

            // Set editing to true to edit the current project
            this.ModifyingProject = true;
        }

        public void OnPostUpdateProject(string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);

            // Capture the values of the old project
            Guid projectGuid = this.EditingProject.ProjectGUID;
            Guid eventGuid = this.AssociatedEvent.EventGUID;
            List<ProjectInstance> projectInstances = this.EditingProject.ProjectInstances;
            string projectName = Request.Form["projectNameText"];
            string projectDescription = Request.Form["projectDescriptionText"];

            // If it is a new project, insert
            if (this.NewProject)
            {
                SqlCommand projectInsert = new SqlCommand(
                    "insert into Task (TaskGUID, EventGUID, TaskName, TaskDescription) " +
                    "values(@TaskGUID, @EventGUID, @TaskName, @TaskDescription)");
                projectInsert.Parameters.AddWithValue("@TaskGUID", projectGuid);
                projectInsert.Parameters.AddWithValue("@EventGUID", eventGuid);
                projectInsert.Parameters.AddWithValue("@TaskName", projectName);
                projectInsert.Parameters.AddWithValue("@TaskDescription", projectDescription);

                SQLWorker.ExecuteNonQuery(projectInsert);

                // Reload the project editor with the new project loaded
                Response.Redirect($"/ProjectEditor/{eventGuid}/{projectGuid}/");
            }
            // If it is not a new project, update
            else
            {
                SqlCommand projectUpdate = new SqlCommand(
                    "update Task " +
                    "set TaskName = @TaskName, TaskDescription = @TaskDescription " +
                    "where TaskGUID = @TaskGUID");
                projectUpdate.Parameters.AddWithValue("@TaskName", projectName);
                projectUpdate.Parameters.AddWithValue("@TaskDescription", projectDescription);
                projectUpdate.Parameters.AddWithValue("@TaskGUID", projectGuid);

                SQLWorker.ExecuteNonQuery(projectUpdate);
            }

            // Update the current project to the updated values
            this.EditingProject = new Project(projectName, projectDescription, projectInstances, projectGuid, eventGuid);
            this.ModifyingProject = false;
        }

        public void OnPostReturnButton (string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);

            // Get the organizer's UserGUID, then send the user back to the Event Editor
            // This is a scuffed method, but since the only way to get here is by being the organizer
            // of the current event, it will have to do for now. I'll return with a better strat if there
            // is time later

            Guid eventGuid = this.AssociatedEvent.EventGUID;

            // Get the UserGuid associated to the organizer of the event
            SqlCommand userQuery = new SqlCommand("select top 1 UserGUID from Individual where EventGUID = @EventGUID");
            userQuery.Parameters.AddWithValue("@EventGUID", eventGuid);

            DataTable userResult = SQLWorker.ExecuteQuery(userQuery);

            Guid userGuid = (Guid)userResult.Rows[0][0];

            Response.Redirect($"/EventEditor/{eventGuid}/{userGuid}");
        }

        public void OnPostNewInstance (string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);
            this.AddingInstance = true;
        }

        public void OnPostAddInstance (string eventId, string? projectId)
        {
            this.SetValues(eventId, projectId);

            DateTime instanceTime = DateTime.Parse(Request.Form["newInstanceTime"]);
            string[] instanceVolunteers = Request.Form["volunteerCheckbox"];
            Guid instanceGuid = Guid.NewGuid();

            // Make the insertion into ProjectInstance
            SqlCommand instanceCommand = new SqlCommand(
                "insert into TaskInstance " +
                "(InstanceGUID, TaskGUID, StartDateTime) " +
                "values(@InstanceGUID, @TaskGUID, @InstanceTime)");
            instanceCommand.Parameters.AddWithValue("@InstanceGUID", instanceGuid);
            instanceCommand.Parameters.AddWithValue("@TaskGUID", this.EditingProject.ProjectGUID);
            instanceCommand.Parameters.AddWithValue("@InstanceTime", instanceTime);

            SQLWorker.ExecuteNonQuery(instanceCommand);

            for (int i = 0; i < instanceVolunteers.Length; i++)
            {
                SqlCommand volunteerCommand = new SqlCommand(
                    "insert into VolunteerAssignment " +
                    "(AssignmentGUID, InstanceGUID, IndividualGUID) " +
                    "values(newid(), @InstanceGUID, @IndividualGUID)");
                volunteerCommand.Parameters.AddWithValue("@InstanceGUID", instanceGuid);
                volunteerCommand.Parameters.AddWithValue("@IndividualGUID", Guid.Parse(instanceVolunteers[i]));

                SQLWorker.ExecuteNonQuery(volunteerCommand);
            }

            this.AddingInstance = false;
        }

        private void SetValues (string eventId, string? projectId)
        {
            this.AssociatedEvent = new Event(Guid.Parse(eventId));

            // If projectId is not null, assign the values
            if (projectId == null)
            {
                this.ModifyingProject = true;
                this.NewProject = true;
            }
            else
            {
                this.EditingProject = new Project(Guid.Parse(projectId));
                this.ModifyingProject = false;
                this.NewProject = false;
            }
        }
    }
}

VolunteerOrganizer/Pages/EventCreator.cshtml
@page "{userId}"
@model VolunteerOrganizer.Pages.EventCreatorModel
@{
}

<body>
    <div class="divStyle">
        <h4>Please enter the details for your event:</h4>

        <form method="post">
            <label for="eventNameText">
                Event Name:
                <input type="text" name="eventNameText" />
            </label>

            <label for="eventDescriptionText">
                Event Description:
                <input type="text" name="eventDescriptionText" />
            </label>

            <label for="eventStartDate">
                Start Date:
                <input type="date" name="eventStartDate" />
            </label>

            <label for="eventEndDate">
                End Date:
                <input type="date" name="eventEndDate" />
            </label>

            <input class="submitStyle" type="submit" />
        </form>
    </div>
</body>

VolunteerOrganizer/Pages/EventEditor.cshtml
@page "{eventId}/{userId}"
@model VolunteerOrganizer.Pages.EventEditorModel
@{
}

<!-- Event Info -->
@if (!@Model.Editing)
{    
    <div id="eventInfoDisplay" class="divStyle">
        <p class="blockStyle" id="eventName">Event Name: @Model.CurrentEvent.EventName</p>
        <p class="blockStyle" id="eventDescription">Event Description: @Model.CurrentEvent.EventDescription</p>
        <p class="blockStyle" id="eventStartDate">Start Date: @Model.CurrentEvent.StartDate</p>
        <p class="blockStyle" id="eventEndDate">End Date: @Model.CurrentEvent.EndDate</p>
        <p class="blockStyle" id="eventSearchKey">Event Key: @Model.CurrentEvent.SearchKey. Share this with your volunteers so they can sign up for your event.</p>
    </div>

    <form method="post">
        <input type="submit" name="editButton" asp-page-handler="EditEvent" value="Edit Event" class="submitStyle">
    </form>
}
else
{
    <div id="eventEditMenu" class="divStyle">
        <form method="post">
            <label for="eventNameText">
                Event Name:
                <input type="text" name="eventNameText" value="@Model.CurrentEvent.EventName">
            </label>

            <lebel for="eventDescriptionText">
                Event Description:
                <input type="text" name="eventDescriptionText" value="@Model.CurrentEvent.EventDescription">
            </lebel>

            <label for="eventStartDate">
                Start Date:
                <input type="date" name="eventStartDate" value="@Model.CurrentEvent.StartDate">
            </label>

            <label for="eventEndDate">
                End Date:
                <input type="date" name="eventEndDate" value="@Model.CurrentEvent.EndDate">
            </label>

            <input type="submit" asp-page-handler="FinishEditing" value="Submit" class="submitStyle">
        </form>
    </div>
}

<!-- Task Info -->
<div id="taskMenu" class="divStyle">
    @if (@Model.EventProjects.Count > 0)
        {
        
        <ul id="currentProjects">
            @for (int i = 0; i < @Model.EventProjects.Count; i++)
            {
                <!-- This a tag will go to the project editor once that exists -->
                <li><a href="/ProjectEditor/@Model.CurrentEvent.EventGUID/@Model.EventProjects[i].ProjectGUID">@Model.EventProjects[i].ProjectName</a></li>
            }
        </ul>
    }
    else
    {
        <p>This event currently has no projects.</p>
    }

    <form method="post">
        <input type="submit" value="Create new Project" asp-page-handler="NewProject" class="submitStyle" />
    </form>
</div>

<!-- Volunteer Info -->
<div id="volunteerMenu" class="divStyle">
    <p>Event Volunteers:</p>
    @if (@Model.EventVolunteers.Count > 0)
    {        
        <ul id="volunteerList">
            @for (int i = 0; i < @Model.EventVolunteers.Count; i++)
            {
                <li>@Model.EventVolunteers[i].Item2</li>
            }
        </ul>
    }
    else
    {
        <p>No volunteers currently assigned.</p>
    }
</div>

VolunteerOrganizer/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolunteerOrganizer.styles.css" asp-append-version="true" />
</head>
<body>
    <!-- Central Text -->
    <div class="text-center divStyle">
        <h4 class="textColor">Welcome to the Volunteer Organizer.</h4>
        <h5 class="textColor">Click to <a href="/LogInPage/">log in</a>, or <a href="/UserRegistrationPage/">register an account.</a></h5>
    </div>
</body>

VolunteerOrganizer/Pages/InstanceEditor.cshtml
@page "{projectId}/{instanceId?}"
@model VolunteerOrganizer.Pages.InstanceEditorModel
@{
}

<h3>Project Name: @Model.WorkingProject.ProjectName</h3>

@if (!@Model.ModifyingInstance) 
{
    <div id="instanceDataMenu" class="divStyle">
        <p>Instance Time: @Model.WorkingInstance.InstanceTime</p>
    </div>

    <form method="post">
        <input type="submit" value="Edit Instance" asp-page-handler="ModifyInstance" class="submitStyle">
    </form>
}
else 
{
    <div id="instanceEditMenu" class="divStyle">
        <form method="post">
            <label for="instanceTime">
                Instance Time: 
                <input type="time" name="instanceTime" value="@Model.WorkingInstance.InstanceTime">
            </label>

            <input type="submit" value="Save Instance" asp-page-handler="SaveInstance" class="submitStyle">
        </form>
    </div>
}

VolunteerOrganizer/Pages/LogInPage.cshtml
@page
@model VolunteerOrganizer.Pages.LogInPageModel
@{
}

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VolunteerOrganizer.styles.css" asp-append-version="true" />
</head>
<body>
    <div id="logInMenu" class="divStyle">
        <h4>Please enter your login details:</h4>

        @if (@Model.LogInError)
        {
            <p>Your email and password were incorrect. Please try again.</p>
        }

        <form method="post">
            <label for="userEmailText" class="textColor">
                Email:
                <input type="text" name="userEmailText" />
            </label>
            <label for="userPasswordText" class="textColor">
                Password:
                <input type="text" name="userPasswordText" />
            </label>
            <input type="submit" class="submitStyle" />
        </form>
    </div>
</body>

VolunteerOrganizer/Pages/LoggedInPage.cshtml
@page "{userId?}"
@model VolunteerOrganizer.Pages.LoggedInPageModel
@{
}
<div class="divStyle">
    <p>Hello there, @Model.LoggedInUser.FirstName @Model.LoggedInUser.LastName</p>
</div>

<div id="organizerMenu" class="divStyle">
    @if (@Model.OrganizerEvents.Count != 0)
    {    
        <p>The events you are organizing:</p>
        @for (int i = 0; i < @Model.OrganizerEvents.Count; i++) 
        {
            <a class="blockStyle" href="/EventEditor/@Model.OrganizerEvents[i].Item2/@Model.LoggedInUser.UserGuid">@Model.OrganizerEvents[i].Item1</a>
        }
    }
    else 
    {
        <p class="blockStyle">You are not organizing any events yet.</p>
    }

    <a href="/EventCreator/@Model.LoggedInUser.UserGuid">Click here to create a new event.</a>
</div>

<div id="volunteerMenu" class="divStyle">
    @if (@Model.VolunteerEvents.Count != 0)
    {
        @for (int i = 0; i < @Model.VolunteerEvents.Count; i++)
        {
            <a class="blockStyle" href="/VolunteerView/@Model.VolunteerEvents[i].Item2/@Model.LoggedInUser.UserGuid/">@Model.VolunteerEvents[i].Item1</a>
        }
    }
    else
    {
        <p class="blockStyle">You are not volunteering for any events yet.</p>
    }

    <p>Enter the event key provided by your event's organizer here to volunteer for an event.</p>
    <form method="post">
        <label for="searchKeyText">
            Event Key:
            <input type="text" name="searchKeyText"/>
        </label>
        <input type="submit" asp-page-handler="AddVolunteer" class="submitStyle" value="Volunteer for this Event" />
    </form>
</div>

VolunteerOrganizer/Pages/ProjectEditor.cshtml
@page "{eventId}/{projectId?}"
@model VolunteerOrganizer.Pages.ProjectEditorModel
@{
}
<!-- Return to Event Editor Button -->
<form method="post">
    <label for="returnButton">
        Return to Event Editor:
        <input type="submit" name="returnButton" class="submitStyle" asp-page-handler="ReturnButton" />
    </label>
</form>


@if (!@Model.ModifyingProject)
{    
    <!-- Project Data Menu -->
    <div id="projectDataMenu" class="divStyle">
        <p>Project Name: @Model.EditingProject.ProjectName</p>
        <p>Project Description: @Model.EditingProject.ProjectDescription</p>

        <form method="post">
            <input type="submit" class="submitStyle" asp-page-handler="EditProject">
        </form>
    </div>
}
else
{
    <!-- Project Editing Menu -->
    <div id="projectEditingMenu" class="divStyle">
        <form method="post">
            <label for="projectNameText">
                Project Name:
                <input type="text" name="projectNameText" value="@Model.EditingProject.ProjectName">
            </label>

            <label for="projectDescriptionText">
                Project Description:
                <input type="text" name="projectDescriptionText" value="@Model.EditingProject.ProjectDescription">
            </label>

            <input type="submit" class="submitStyle" asp-page-handler="UpdateProject">
        </form>
    </div>
}

<!-- Instance Editing Menu -->
<div id="instanceDataMenu" class="divStyle">
    @if (@Model.EditingProject.ProjectInstances.Count == 0)
    {
        <p>This project does not have any instances.</p>
    }

    <ul>
        @for (int i = 0; i < @Model.EditingProject.ProjectInstances.Count; i++)
        {
            <li>@Model.EditingProject.ProjectInstances[i].InstanceTime</li>
            <ul>
            @for (int x = 0; x < @Model.EditingProject.ProjectInstances[i].AssignedVolunteers.Count; x++)
                {
                    <li>@Model.EditingProject.ProjectInstances[i].AssignedVolunteers[x].GetName()</li>
                }
            </ul>
            }
    </ul>
    @if (!@Model.ModifyingProject)
    {        
        <form method="post">
            <input type="submit" name="newInstanceButton" value="Add New Instance" class="submitStyle" asp-page-handler="NewInstance" />
        </form>
    }
</div>

<!-- Add Instance Menu -->

<div id="addInstanceMenu" class="divStyle">
    @if (@Model.AddingInstance)
    {
           <form method="post">
               <label for="newInstanceTime">
                   Instance Time:
                   <input type="date" name="newInstanceTime">
               </label>
               
                @for (int i = 0; i < @Model.AssociatedEvent.GetAssignedVolunteers().Count; i++)
                {
                    <label for="volunteerCheckbox">
                        @Model.AssociatedEvent.GetAssignedVolunteers()[i].Item1;
                        <input type="checkbox" name="volunteerCheckbox" value="@Model.AssociatedEvent.GetAssignedVolunteers()[i].Item2">
                    </label>
                }

                <input type="submit" asp-page-handler="AddInstance" class="submitStyle" value="Add Project Instance">
           </form>
    }
</div>

VolunteerOrganizer/Pages/UserRegistrationPage.cshtml
@page
@model VolunteerOrganizer.Pages.UserRegistrationPageModel
@{
}

<div id="registrationMenu" class="divStyle">
    <h4>User Registration</h4>
    <form id="registrationForm" method="post">
        @if (@Model.Error)
        {
            <p>@Model.ErrorMessage</p>
        }
        <label for="userEmailText">
            Email:
            <input type="text" name="userEmailText"/>
        </label>

        <label for="userPasswordText">
            Password:
            <input type="text" name="userPasswordText" />
        </label>

        <label for="userFirstNameText">
            First Name:
            <input type="text" name="userFirstNameText" />
        </label>

        <label for="userLastNameText">
            Last Name:
            <input type="text" name="userLastNameText" />
        </label>

        <label for="userPhoneNumberText">
            Phone Number:
            <input type="text" name="userPhoneNumberText" />
        </label>
        <input type="submit" class="submitStyle" />
    </form>
</div>

VolunteerOrganizer/Pages/VolunteerView.cshtml
@page "{eventId}/{individualId}"
@model VolunteerOrganizer.Pages.VolunteerViewModel
@{
}

<div class="divStyle">
    <h3>Project Assignments for @Model.VolunteerUser.FirstName @Model.VolunteerUser.LastName</h3>

    @if (@Model.VolunteerProjects.Count == 0) 
    {
        <p>You have not been assigned any projects. Hang tight until your event's organizer gives you some projects.</p>
    }
    else 
    {
        @for (int i = 0; i < @Model.VolunteerProjects.Count; i++)
        {
            <p>@Model.VolunteerProjects[i].Item1</p>
            <p>@Model.VolunteerProjects[i].Item2</p>
            <p>@Model.VolunteerProjects[i].Item3</p>
        }
    }
</div>